AllCops:
  Excludes:
    - db/**
  Enabled: true


# Wir haben versucht uns an die LineLength 80 zu halten
# Nachdem wir fast alle line to long fehler behoben haben haben wir
# uns dazu entschieden das die verbliebenden lines die über 80 sind
# ok sind
#Metrics/LineLength:
#  Max: 100