AllCops:
  Excludes:
    - db/**
    # mussen nochmal ueberarbeitet werden
    - app/models/user.rb
    - config/initializers/simple_form_bootstrap.rb
    - test/test_helper.rb
    # Die specs brauchen nicht ueberprueft werden
    # wenn wir Sie grade bearbeiten
    - spec/**
  Enabled: true



# Wir haben versucht uns an die LineLength 80 zu halten
# Nachdem wir fast alle line to long fehler behoben haben haben wir
# uns dazu entschieden das die verbliebenden lines ok sind
Metrics/LineLength:
  Max: 102

# Wir haben es auf 12 erhoeht weil wir den Fehler finden das
# Es nicht schlimm ist wenn eine funktion keine 10 zeilen hat
Metrics/MethodLength:
  Max: 12

Lint/DuplicatedKey:
    Exclude:
      - 'app/models/carevent.rb'
      - 'app/models/roomplan.rb'
      - 'app/models/vacationplan.rb'

Metrics/AbcSize:
    Max: 17