# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 248ff8a7126dad8e0025ae4ddd75eb7a93e5b234037861009d41699618add907af3c96907e3eb7d1bd295425e823e1ff1e8e3be2f57d44b2942c455fc9f32f4c

test:
  secret_key_base: ede515bf5089dbcdc38159e7100b1b414a1dca22b030fb11bacafad72631bfb52f9cdd72137a8c9d763f8069849ee039fca1493072267d65d583a180f43573d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
