require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CareventsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Carevent. As you add validations to Carevent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CareventsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    xit 'assigns all carevents as @carevents' do
      carevent = Carevent.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:carevents)).to eq([carevent])
    end
  end

  describe 'GET #show' do
    xit 'assigns the requested carevent as @carevent' do
      carevent = Carevent.create! valid_attributes
      get :show, { id: carevent.to_param }, valid_session
      expect(assigns(:carevent)).to eq(carevent)
    end
  end

  describe 'GET #new' do
    xit 'assigns a new carevent as @carevent' do
      get :new, {}, valid_session
      expect(assigns(:carevent)).to be_a_new(Carevent)
    end
  end

  describe 'GET #edit' do
    xit 'assigns the requested carevent as @carevent' do
      carevent = Carevent.create! valid_attributes
      get :edit, { id: carevent.to_param }, valid_session
      expect(assigns(:carevent)).to eq(carevent)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      xit 'creates a new Carevent' do
        expect do
          post :create, { carevent: valid_attributes }, valid_session
        end.to change(Carevent, :count).by(1)
      end

      xit 'assigns a newly created carevent as @carevent' do
        post :create, { carevent: valid_attributes }, valid_session
        expect(assigns(:carevent)).to be_a(Carevent)
        expect(assigns(:carevent)).to be_persisted
      end

      xit 'redirects to the created carevent' do
        post :create, { carevent: valid_attributes }, valid_session
        expect(response).to redirect_to(Carevent.last)
      end
    end

    context 'with invalid params' do
      xit 'assigns a newly created but unsaved carevent as @carevent' do
        post :create, { carevent: invalid_attributes }, valid_session
        expect(assigns(:carevent)).to be_a_new(Carevent)
      end

      xit "re-renders the 'new' template" do
        post :create, { carevent: invalid_attributes }, valid_session
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      xit 'updates the requested carevent' do
        carevent = Carevent.create! valid_attributes
        put :update, { id: carevent.to_param, carevent: new_attributes }, valid_session
        carevent.reload
        skip('Add assertions for updated state')
      end

      xit 'assigns the requested carevent as @carevent' do
        carevent = Carevent.create! valid_attributes
        put :update, { id: carevent.to_param, carevent: valid_attributes }, valid_session
        expect(assigns(:carevent)).to eq(carevent)
      end

      xit 'redirects to the carevent' do
        carevent = Carevent.create! valid_attributes
        put :update, { id: carevent.to_param, carevent: valid_attributes }, valid_session
        expect(response).to redirect_to(carevent)
      end
    end

    context 'with invalid params' do
      xit 'assigns the carevent as @carevent' do
        carevent = Carevent.create! valid_attributes
        put :update, { id: carevent.to_param, carevent: invalid_attributes }, valid_session
        expect(assigns(:carevent)).to eq(carevent)
      end

      xit "re-renders the 'edit' template" do
        carevent = Carevent.create! valid_attributes
        put :update, { id: carevent.to_param, carevent: invalid_attributes }, valid_session
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    xit 'destroys the requested carevent' do
      carevent = Carevent.create! valid_attributes
      expect do
        delete :destroy, { id: carevent.to_param }, valid_session
      end.to change(Carevent, :count).by(-1)
    end

    xit 'redirects to the carevents list' do
      carevent = Carevent.create! valid_attributes
      delete :destroy, { id: carevent.to_param }, valid_session
      expect(response).to redirect_to(carevents_url)
    end
  end
end
