require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RoomplansController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Roomplan. As you add validations to Roomplan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RoomplansController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    xit 'assigns all roomplans as @roomplans' do
      roomplan = Roomplan.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:roomplans)).to eq([roomplan])
    end
  end

  describe 'GET #show' do
    xit 'assigns the requested roomplan as @roomplan' do
      roomplan = Roomplan.create! valid_attributes
      get :show, { id: roomplan.to_param }, valid_session
      expect(assigns(:roomplan)).to eq(roomplan)
    end
  end

  describe 'GET #new' do
    xit 'assigns a new roomplan as @roomplan' do
      get :new, {}, valid_session
      expect(assigns(:roomplan)).to be_a_new(Roomplan)
    end
  end

  describe 'GET #edit' do
    xit 'assigns the requested roomplan as @roomplan' do
      roomplan = Roomplan.create! valid_attributes
      get :edit, { id: roomplan.to_param }, valid_session
      expect(assigns(:roomplan)).to eq(roomplan)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      xit 'creates a new Roomplan' do
        expect do
          post :create, { roomplan: valid_attributes }, valid_session
        end.to change(Roomplan, :count).by(1)
      end

      xit 'assigns a newly created roomplan as @roomplan' do
        post :create, { roomplan: valid_attributes }, valid_session
        expect(assigns(:roomplan)).to be_a(Roomplan)
        expect(assigns(:roomplan)).to be_persisted
      end

      xit 'redirects to the created roomplan' do
        post :create, { roomplan: valid_attributes }, valid_session
        expect(response).to redirect_to(Roomplan.last)
      end
    end

    context 'with invalid params' do
      xit 'assigns a newly created but unsaved roomplan as @roomplan' do
        post :create, { roomplan: invalid_attributes }, valid_session
        expect(assigns(:roomplan)).to be_a_new(Roomplan)
      end

      xit "re-renders the 'new' template" do
        post :create, { roomplan: invalid_attributes }, valid_session
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      xit 'updates the requested roomplan' do
        roomplan = Roomplan.create! valid_attributes
        put :update, { id: roomplan.to_param, roomplan: new_attributes }, valid_session
        roomplan.reload
        skip('Add assertions for updated state')
      end

      it 'assigns the requested roomplan as @roomplan' do
        roomplan = Roomplan.create! valid_attributes
        put :update, { id: roomplan.to_param, roomplan: valid_attributes }, valid_session
        expect(assigns(:roomplan)).to eq(roomplan)
      end

      xit 'redirects to the roomplan' do
        roomplan = Roomplan.create! valid_attributes
        put :update, { id: roomplan.to_param, roomplan: valid_attributes }, valid_session
        expect(response).to redirect_to(roomplan)
      end
    end

    context 'with invalid params' do
      xit 'assigns the roomplan as @roomplan' do
        roomplan = Roomplan.create! valid_attributes
        put :update, { id: roomplan.to_param, roomplan: invalid_attributes }, valid_session
        expect(assigns(:roomplan)).to eq(roomplan)
      end

      xit "re-renders the 'edit' template" do
        roomplan = Roomplan.create! valid_attributes
        put :update, { id: roomplan.to_param, roomplan: invalid_attributes }, valid_session
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    xit 'destroys the requested roomplan' do
      roomplan = Roomplan.create! valid_attributes
      expect do
        delete :destroy, { id: roomplan.to_param }, valid_session
      end.to change(Roomplan, :count).by(-1)
    end

    xit 'redirects to the roomplans list' do
      roomplan = Roomplan.create! valid_attributes
      delete :destroy, { id: roomplan.to_param }, valid_session
      expect(response).to redirect_to(roomplans_url)
    end
  end
end
